GET http://localhost:3001/

###

GET http://localhost:3000/stock

###

POST http://localhost:3000/stock
Content-Type: application/json

{
    "brand": "unbranded",
    "price": 9,
    "quant": 2,
    "desc": "dgjhffghfg",
    "size": "null"
}

###

POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "admin@randomcorporate.com",
    "password": "admin",
    "name": "admin",
    "phoneNumber": "1234567890"
}

###

POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "admin@randomcorporate.com",
    "password": "admin"
}